require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe MyAppsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # MyApp. As you add validations to MyApp, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { title: "My app", javascript_origins: "http://etc.com" }
  }

  let(:my_app){ FactoryGirl.create(:my_app)}

  let(:invalid_attributes) {
    { title: "" }
  }

  before :each do
    request.session[:user_id] = my_app.user.id
  end

  describe "GET #new" do
    it "assigns a new my_app as @my_app" do
      get :new, {}
      expect(assigns(:my_app)).to be_a_new(MyApp)
    end
  end

  describe "GET #edit" do
    it "assigns the requested my_app as @my_app" do
      put :edit, {:id => my_app.to_param}
      expect(assigns(:my_app)).to eq(my_app)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new MyApp" do
        expect {
          post :create, {:my_app => valid_attributes}
        }.to change(MyApp, :count).by(1)
      end

      it "assigns a newly created my_app as @my_app" do
        post :create, {:my_app => valid_attributes}
        expect(assigns(:my_app)).to be_a(MyApp)
        expect(assigns(:my_app)).to be_persisted
      end

      it "redirects to the created my_app" do
        post :create, {:my_app => valid_attributes}
        expect(response).to redirect_to("/")
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved my_app as @my_app" do
        post :create, {:my_app => invalid_attributes}
        expect(assigns(:my_app)).to be_a_new(MyApp)
      end

      it "re-renders the 'new' template" do
        post :create, {:my_app => invalid_attributes}
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        { title: "update title" }
      }

      it "updates the requested my_app" do
        get :update, {:id => my_app.to_param, :my_app => new_attributes}
        my_app.reload
        expect(my_app.title).to eq("update title")
      end

      it "assigns the requested my_app as @my_app" do
        put :update, {:id => my_app.to_param, :my_app => valid_attributes}
        expect(assigns(:my_app)).to eq(my_app)
      end

      it "redirects to the my_app" do
        put :update, {:id => my_app.to_param, :my_app => valid_attributes}
        expect(response).to redirect_to("/")
      end
    end

    context "with invalid params" do
      it "assigns the my_app as @my_app" do
        put :update, {:id => my_app.to_param, :my_app => invalid_attributes}
        expect(assigns(:my_app)).to eq(my_app)
      end

      it "re-renders the 'edit' template" do
        put :update, {:id => my_app.to_param, :my_app => invalid_attributes}
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested my_app" do
      expect {
        delete :destroy, {:id => my_app.to_param}
      }.to change(MyApp, :count).by(-1)
    end

    it "redirects to the my_apps list" do
      delete :destroy, {:id => my_app.to_param}
      expect(response).to redirect_to("/")
    end
  end

end
